name: "plugins-ca-common"

# These tests are slow to run so we only run them when necessary rather than every pull request.

on:
  pull_request:
    paths:
      - .github/workflows/plugins-ca-common.yaml
      - 'plugins/ca-common/**'
      - 'process-compose.yaml' # Removal of this file will cause tests to fail.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jetify-com/devbox-install-action@v0.14.0
      - run: devbox run test plugins/ca-common
